const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  await prisma.listing.deleteMany();

  await prisma.listing.createMany({
    data: [
      // CS2
      { id: 'cs2-prime-uae-1', title: 'CS2 Prime Account — Gold Nova', game: 'Counter-Strike 2', rank: 'Gold Nova III', region: 'UAE 🇦🇪', price: 14.99, level: '32', wins: '187', hours: '420', type: 'Prime', instant: true, description: 'Clean CS2 Prime account with Gold Nova III rank. Never cheated, no VAC bans. Comes with original email. UAE server region. Instant delivery after payment.', includes: ['Original Email Access', 'Prime Status', 'Clean VAC Record', '24/7 Support', 'Instant Delivery'] },
      { id: 'cs2-prime-eu-1', title: 'CS2 Prime Account — Master Guardian', game: 'Counter-Strike 2', rank: 'Master Guardian II', region: 'EU 🇪🇺', price: 19.99, level: '45', wins: '230', hours: '560', type: 'Prime', instant: true, description: 'Clean CS2 Prime account with Master Guardian II rank on EU servers. Never cheated, no VAC bans. Original email included.', includes: ['Original Email Access', 'Prime Status', 'Clean VAC Record', '24/7 Support', 'Instant Delivery'] },
      { id: 'cs2-faceit-na-1', title: 'CS2 Faceit Account — Level 5', game: 'Counter-Strike 2', rank: 'Faceit Level 5', region: 'NA 🇺🇸', price: 24.99, level: '38', wins: '198', hours: '480', type: 'Faceit', instant: true, description: 'CS2 Faceit Level 5 account on NA servers. Clean account, original email included.', includes: ['Original Email Access', 'Faceit Level 5', 'Clean Account', '24/7 Support', 'Instant Delivery'] },
      { id: 'cs2-prime-sea-1', title: 'CS2 Prime Account — Legendary Eagle', game: 'Counter-Strike 2', rank: 'Legendary Eagle', region: 'SEA 🌏', price: 29.99, level: '52', wins: '310', hours: '720', type: 'Prime', instant: true, description: 'Clean CS2 Prime Legendary Eagle account on SEA servers. Never cheated, no VAC bans. Original email included.', includes: ['Original Email Access', 'Prime Status', 'Legendary Eagle Rank', '24/7 Support', 'Instant Delivery'] },
      { id: 'cs2-highrank-uae-1', title: 'CS2 High Rank — Supreme', game: 'Counter-Strike 2', rank: 'Supreme Master First Class', region: 'UAE 🇦🇪', price: 39.99, level: '68', wins: '420', hours: '1100', type: 'Prime', instant: true, description: 'CS2 Supreme Master First Class account on UAE servers. High level, clean account, original email included.', includes: ['Original Email Access', 'Prime Status', 'Supreme Rank', '24/7 Support', 'Instant Delivery'] },
      { id: 'cs2-faceit-eu-1', title: 'CS2 Faceit Account — Level 8', game: 'Counter-Strike 2', rank: 'Faceit Level 8', region: 'EU 🇪🇺', price: 49.99, level: '72', wins: '510', hours: '1400', type: 'Faceit', instant: true, description: 'CS2 Faceit Level 8 account on EU servers. High level competitive account, clean, original email included.', includes: ['Original Email Access', 'Faceit Level 8', 'Clean Account', '24/7 Support', 'Instant Delivery'] },
      // Valorant
      { id: 'valorant-silver-uae-1', title: 'Valorant Smurf Account — Silver', game: 'Valorant', rank: 'Silver 2', region: 'UAE 🇦🇪', price: 9.99, level: '45', wins: '98', hours: '210', type: 'Ranked', instant: true, description: 'Clean Valorant Silver 2 account on UAE server. Never banned, original email included.', includes: ['Original Email Access', 'Silver 2 Rank', 'Clean Account', '24/7 Support', 'Instant Delivery'] },
      { id: 'valorant-gold-eu-1', title: 'Valorant Smurf Account — Gold', game: 'Valorant', rank: 'Gold 1', region: 'EU 🇪🇺', price: 14.99, level: '52', wins: '145', hours: '320', type: 'Ranked', instant: true, description: 'Clean Valorant Gold 1 account on EU server. Never banned, original email included.', includes: ['Original Email Access', 'Gold 1 Rank', 'Clean Account', '24/7 Support', 'Instant Delivery'] },
      { id: 'valorant-platinum-na-1', title: 'Valorant Ranked Account — Platinum', game: 'Valorant', rank: 'Platinum 2', region: 'NA 🇺🇸', price: 19.99, level: '61', wins: '198', hours: '450', type: 'Ranked', instant: true, description: 'Clean Valorant Platinum 2 account on NA server. Never banned, original email included.', includes: ['Original Email Access', 'Platinum 2 Rank', 'Clean Account', '24/7 Support', 'Instant Delivery'] },
      { id: 'valorant-diamond-sea-1', title: 'Valorant Ranked Account — Diamond', game: 'Valorant', rank: 'Diamond 1', region: 'SEA 🌏', price: 29.99, level: '70', wins: '245', hours: '620', type: 'Ranked', instant: true, description: 'Clean Valorant Diamond 1 account on SEA server. Never banned, original email included.', includes: ['Original Email Access', 'Diamond 1 Rank', 'Clean Account', '24/7 Support', 'Instant Delivery'] },
      { id: 'valorant-immortal-uae-1', title: 'Valorant Immortal Account — UAE', game: 'Valorant', rank: 'Immortal 2', region: 'UAE 🇦🇪', price: 49.99, level: '78', wins: '312', hours: '890', type: 'Ranked', instant: true, description: 'Valorant Immortal 2 account on UAE server. 85 skins including rare battlepass skins. Clean account, never banned.', includes: ['Original Email Access', '85 Skins', 'Immortal 2 Rank', 'Clean Account', 'Instant Delivery'] },
      { id: 'valorant-radiant-eu-1', title: 'Valorant Top Rank — Radiant', game: 'Valorant', rank: 'Radiant', region: 'EU 🇪🇺', price: 99.99, level: '95', wins: '489', hours: '1200', type: 'Ranked', instant: true, description: 'Valorant Radiant account on EU server. Top 500 players. Rare skins included. Never banned.', includes: ['Original Email Access', 'Radiant Rank', 'Rare Skins', 'Clean Account', 'Instant Delivery'] },
      // GTA V
      { id: 'gta-v-modded-uae-1', title: 'GTA V Modded Account — Level 120', game: 'GTA V Online', rank: 'Level 120', region: 'UAE 🇦🇪', price: 14.99, level: '120', wins: '-', hours: '210', type: 'Modded', instant: true, description: 'GTA V Online modded account with Level 120, $50M cash. Available for PC. Instant delivery after payment.', includes: ['Level 120', '$50M Cash', 'Clean Account', '24/7 Support', 'Instant Delivery'] },
      { id: 'gta-v-modded-na-1', title: 'GTA V Modded Account — Level 200', game: 'GTA V Online', rank: 'Level 200', region: 'NA 🇺🇸', price: 19.99, level: '200', wins: '-', hours: '340', type: 'Modded', instant: true, description: 'GTA V Online modded account with Level 200, $200M cash, all properties unlocked.', includes: ['Level 200', '$200M Cash', 'All Properties', 'Rare Vehicles', 'Instant Delivery'] },
      { id: 'gta-v-fullunlock-eu-1', title: 'GTA V Full Unlock — Level 300', game: 'GTA V Online', rank: 'Level 300', region: 'EU 🇪🇺', price: 29.99, level: '300', wins: '-', hours: '520', type: 'Full Unlock', instant: true, description: 'GTA V Online Level 300 account with all vehicles unlocked. Available for PC.', includes: ['Level 300', 'All Vehicles', 'Full Unlock', '24/7 Support', 'Instant Delivery'] },
      { id: 'gta-v-money-sea-1', title: 'GTA V Money Account — Level 150', game: 'GTA V Online', rank: 'Level 150', region: 'SEA 🌏', price: 24.99, level: '150', wins: '-', hours: '280', type: 'Money', instant: true, description: 'GTA V Online Level 150 account with $100M cash. Available for PC.', includes: ['Level 150', '$100M Cash', 'Clean Account', '24/7 Support', 'Instant Delivery'] },
      { id: 'gta-v-modded-uae-2', title: 'GTA V Modded Account — Level 500', game: 'GTA V Online', rank: 'Level 500', region: 'UAE 🇦🇪', price: 49.99, level: '500', wins: '-', hours: '890', type: 'Modded', instant: true, description: 'GTA V Online Level 500 account with max stats. Available for PC.', includes: ['Level 500', 'Max Stats', 'All Weapons', '24/7 Support', 'Instant Delivery'] },
      { id: 'gta-v-fullunlock-eu-2', title: 'GTA V Full Unlock — Level 8000', game: 'GTA V Online', rank: 'Level 8000', region: 'EU 🇪🇺', price: 79.99, level: '8000', wins: '-', hours: '2100', type: 'Full Unlock', instant: true, description: 'GTA V Online Level 8000 account with everything unlocked. The ultimate GTA V account.', includes: ['Level 8000', 'Everything Unlocked', 'All Vehicles', 'Max Money', 'Instant Delivery'] },
    ]
  });

  console.log('✅ Database seeded with all listings!');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
